package com.distributed.system.project;

import java.awt.*;

public class Descriptor {

    //two types of sensors
    public static final int BASIC_SENSOR=1;
    public static final int ADVANCED_SENSOR=2;

    //4 types of states
    public static final int READY=1;
    public static final int NEW=2;
    public static final int REGISTRED=3;
    public static final int ERROR=4;

    //5 types of sensors by the provided service
    public static final int TEMPERATURE=1;
    public static final int HUMIDITY=2;
    public static final int IMAGE=3;
    public static final int SPEED=4;
    public static final int DIRECTION=5;

    //id generated by the supervisor after registration
    protected String id;

    //the maximum number of request that the sensor can process without errors
    protected int capacity;

    //the number of request processed by the sensor
    protected int nbRequest;

    //the number of request routed by the sensor if it advanced sensor
    //it always 0 if the sensor is a basic sensor
    protected int nbRoutedRequest;

    //the maximum distance to her position where the sensor can get data
    protected double range;

    //the position of the sensor
    protected Point position;

    //the type of variables and the time for each refresh
    Request request;

    public Descriptor() {
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public int getCapacity() {
        return capacity;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    public int getNbRequest() {
        return nbRequest;
    }

    public void setNbRequest(int nbRequest) {
        this.nbRequest = nbRequest;
    }

    public int getNbRoutedRequest() {
        return nbRoutedRequest;
    }

    public void setNbRoutedRequest(int nbRoutedRequest) {
        this.nbRoutedRequest = nbRoutedRequest;
    }

    public double getRange() {
        return range;
    }

    public void setRange(double range) {
        this.range = range;
    }

    public Point getPosition() {
        return position;
    }

    public void setPosition(Point position) {
        this.position = position;
    }

    public Request getRequest() {
        return request;
    }

    public void setRequest(Request request) {
        this.request = request;
    }
}
